config/routes.rb
Rails.application.routes.draw do
  
  root "top#index"
  
  get "about" => "top#about", as: "about"
  
  get "bad_request" => "top#bad_request"
  get "forbidden" => "top#forbidden"
  get "internal_server_error" => "top#internal_server_error"
  
  
  resources :members, only: [:index, :show] do
    get "search", on: :collection
    resources :entries, only: [:index]
  end 
  
  resource :session, only: [:create, :destroy]
  resource :account, only: [:show, :edit, :update]
  resource :password, only: [:show, :edit, :update]
  
  resources :articles, only: [:index, :show]
  
  resources :entries do
    patch "like", "unlike", on: :member
    get "voted", on: :collection
    resources :images, controller: "entry_images" do
      patch :move_higher, :move_lower, on: :member
    end 
  end 
  
  namespace :admin do
    root "top#index"
    resources :members do
      get "search", on: :collection
    end
    resources :articles
  end 
  
end

app/views/shared/_admin_menubar.html.erb
<nav class="menubar" id="admin-menubar">
  <ul>
    <%= menu_link_to "管理者TOP", :admin_root %>
    <%= menu_link_to "会員管理", :admin_members %>
    <%= menu_link_to "ニュース記事管理", :admin_articles %>
    <%= menu_link_to "TOP", :root %>
  </ul>
</nav>

app/views/shared/_errors.html.erb
<% if obj.errors.present? %>

  <div id="errors">
    <h3>エラーがあります</h3>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>

<% end %>

app/views/shared/_footer.html.erb
<%= link_to "このサイトについて", ":about" %>
Copyright (C) <%= link_to "kame.", "http://www" %>
2007-2020

app/views/shared/_header.html.erb
<%= image_tag "logo-31.png", size: "272x48", alt: "member program" %>

<% if current_member %>
  <ul class="account-menu">
    <%= menu_link_to current_member.name + "さん", :account %>
    <%= menu_link_to "ログアウト", :session, method: :delete, data: {confirm: "ログアウトしますか？" } %>
  </ul>
<% end %>


<%= 
  if controller.kind_of?(Admin::Base)
    render "shared/admin_menubar"
  else 
    render "shared/menubar"
  end 
%>

app/views/shared/_login_form.html.erb
<h2>ログイン</h2>

<% if flash.alert %>
  <p class="alert"><%= flash.alert %></p>
<% end %>

<%= form_tag :session, id: "login_form" do %>
  <div>
    <label>ユーザー名：</label>
    <input type="text" name="name">
  </div>
  <div>
    <label>パスワード：</label>
    <input type="password" name="password">
  </div>
  <div>
    <input type="submit" value="ログイン">
  </div>
<% end %>

app/views/shared/_member_form.html.erb
<%= render "shared/errors", obj: @member %>
<table class="attr">
  
  <tr>
    <th><%= form.label :new_profile_picture %></th>
    
    <td>
      <div>
        <%= form.file_field :new_profile_picture %>
      </div>
        
      <% if @member.profile_picture.attached? %>
        <div>
          <%= image_tag @member.profile_picture.variant(resize: "128x128") %>
          <%= form.check_box :remove_profile_picture %>
          <%= form.label :remove_profile_picture %>
        </div>
      <% end %>
    </td>
    
  </tr>
  
  
  <tr>
    <th><%= form.label :number %></th>
    <td><%= form.text_field :number, size: 8 %></td>
  </tr>
  <tr>
    <th><%= form.label :name %></th>
    <td><%= form.text_field :name %></td>
  </tr>
  <tr>
    <th><%= form.label :full_name %></th>
    <td><%= form.text_field :full_name %></td>
  </tr>
  <tr>
    <th><%= Member.human_attribute_name(:gender) %></th>
    <td>
      <%= form.radio_button :gender, 1 %>
      <%= form.label :gender_1 %>
      <%= form.radio_button :gender, 2 %>
      <%= form.label :gender_2 %>
    </td>
  </tr>
  <tr>
    <th><%= form.label :birthday,
              for: "member_birthday_1i" %></th>
    <td><%= form.date_select :birthday,
              start_year: 1940, end_year: Time.current.year,
              use_month_numbers: true %></td>
  </tr>
  <tr>
    <th><%= form.label :email %></th>
    <td><%= form.text_field :email %></td>
  </tr>
  
  <% if @member.new_record? %>
    <tr>
      <th><%= form.label :password, "パスワード" %></th>
      <td><%= form.text_field :password %></td>
    </tr>
  
  <% end %>
  
  <% if controller.kind_of?(Admin::MembersController) %>
    <tr>
      <th><%= Member.human_attribute_name(:administrator) %></th>
      <td>
        <%= form.check_box :administrator, disabled: !current_member.administrator? %>
        <%= form.label :administrator %>
      </td>
    </tr>
  <% end %>
</table>

app/views/shared/_menubar.html.erb
<nav class="menubar">
  <ul>
    <%= menu_link_to "TOP", :root %>
    <%= menu_link_to "ニュース", articles_path %>
    <%= menu_link_to "ブログ", :entries %>
    
    <% if current_member %>
      <%= menu_link_to "会員名簿", :members %>
      
      <% if current_member.administrator? %>
        <%= menu_link_to "管理ページ", :admin_root %>
      <% end %>
    <% end %>
    
  </ul>
</nav>

app/views/shared/_sidebar.html.erb
<%= render "shared/login_form" unless current_member %>

<h2>最新ニュース</h2>


<% 
  articles = Article.visible.order(released_at: :desc).limit(5)
  articles = articles.open_to_the_public unless current_member
%>
<ul>
  <% articles.each do |article| %>
    <li><%= link_to article.title, article %></li>
  <% end %>
</ul>

<h2>会員のブログ</h2>

<%
entries = Entry.readable_for(current_member).order(posted_at: :desc).limit(5)
%>

<ul>
  <% entries.each do |entry| %>
    <li>
      <%= link_to entry.title, entry %> by <%= link_to entry.author.name, member_entries_url(entry.author) %>
    </li>
  <% end %>
</ul>